phases:
  install:
    commands:
      - npm install
      - npm install -g awscli
    working-directory: adminpanel
  build:
    commands:
      - npm run build
    working-directory: adminpanel
  post_build:
    commands:
      - aws s3 sync build/ s3://skbadmin --delete
    working-directory: adminpanel

artifacts:
  files:
    - '**/*'
  base-directory: adminpanel/build
