version: 0.2

phases:
  install:
    commands:
      - echo "Starting installation in ${CODEBUILD_SRC_DIR}"
      - ls -la
      - echo "Copying adminpanel to protected location..."
      - cp -r adminpanel /tmp/adminpanel-build
      - cd /tmp/adminpanel-build && npm install

  build:
    commands:
      - echo "Building from protected location..."
      - cd /tmp/adminpanel-build && npm run build
      - echo "Copying build artifacts..."
      - mkdir -p adminpanel/build
      - cp -r /tmp/adminpanel-build/build/* adminpanel/build/

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync adminpanel/build/ s3://skbadmin --delete

artifacts:
  files:
    - '**/*'
  base-directory: adminpanel/build

cache:
  paths:
    - '/tmp/adminpanel-build/node_modules/**/*'