version: 0.2

phases:
  install:
    commands:
      - echo "Checking directory structure..."
      - ls -la
      - echo "Installing dependencies..."
      - cd adminpanel && npm install

  build:
    commands:
      - echo "Building application..."
      - cd adminpanel && npm run build

  post_build:
    commands:
      - echo "Deploying to S3..."
      - cd adminpanel && aws s3 sync build/ s3://skbadmin --delete

artifacts:
  files:
    - '**/*'
  base-directory: adminpanel/build

cache:
  paths:
    - 'adminpanel/node_modules/**/*'