version: 0.2

phases:
  install:
    commands:
      - echo "Installing admin panel dependencies..."
      - cd adminpanel && npm install
  build:
    commands:
      - echo "Building admin panel..."
      - cd adminpanel && npm run build
  post_build:
    commands:
      - echo "Deploying to S3..."
      - cd adminpanel && aws s3 sync build/ s3://skbadmin --delete

artifacts:
  files:
    - '**/*'
  base-directory: adminpanel/build