version: 0.2

phases:
  install:
    commands:
      - echo "Starting install phase"
      - cd adminpanel && npm install
  
  build:
    commands:
      - echo "Starting build phase"
      - cd adminpanel && npm run build
  
  post_build:
    commands:
      - echo "Starting deployment"
      - cd adminpanel && aws s3 sync build/ s3://skbadmin --delete

artifacts:
  files:
    - '**/*'
  base-directory: adminpanel/build

cache:
  paths:
    - 'adminpanel/node_modules/**/*'

runtime-versions:
  nodejs: 20